export const LOG_IN = "LOG_IN"
export const LOG_OUT = "LOG_OUT"
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS"
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS"
export const LOG_IN_FAIL = "LOG_IN_FAIL"
